######################## GNU General Public License 3.0 ########################
##                                                                            ##
## Copyright (C) 2023 Kevin Matthes                                           ##
##                                                                            ##
## This program is free software: you can redistribute it and/or modify       ##
## it under the terms of the GNU General Public License as published by       ##
## the Free Software Foundation, either version 3 of the License, or          ##
## (at your option) any later version.                                        ##
##                                                                            ##
## This program is distributed in the hope that it will be useful,            ##
## but WITHOUT ANY WARRANTY; without even the implied warranty of             ##
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              ##
## GNU General Public License for more details.                               ##
##                                                                            ##
## You should have received a copy of the GNU General Public License          ##
## along with this program.  If not, see <https://www.gnu.org/licenses/>.     ##
##                                                                            ##
################################################################################

################################################################################
##
##  AUTHOR      Kevin Matthes
##  BRIEF       The CI of this project.
##  COPYRIGHT   GPL-3.0
##  DATE        2023
##  FILE        ci.yml
##  NOTE        See `LICENSE' for full license.
##              See `README.md' for project details.
##
################################################################################

name: ci

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  bors:
    name: bors
    needs:
      - build
      - cffconvert
      - valgrind
    runs-on: ubuntu-latest
    steps:
      - name: success
        run: bash -c 'exit 0'

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.5
        with:
          persist-credentials: false

      - name: gcc
        run: gcc -c -fPIC -std=c99 -Wall -Werror -Wextra -Wpedantic src/*.c

      - name: ar
        run: ar rsv libstrmem.a *.o

      - name: rm
        run: rm -rfv *.o

      - name: cache
        uses: actions/cache/save@v4.0.2
        with:
          key: library-${{ hashFiles ('./libstrmem.a') }}
          path: ./libstrmem.a

  cffconvert:
    name: cffconvert
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.5
        with:
          persist-credentials: false

      - name: cffconvert
        uses: citation-file-format/cffconvert-github-action@2.0.0
        with:
          args: --validate

  valgrind:
    name: valgrind
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: dependencies
        run: sudo apt-get install valgrind -y

      - name: checkout
        uses: actions/checkout@v4.1.5
        with:
          persist-credentials: false

      - name: cache
        uses: actions/cache/restore@v4.0.2
        with:
          key: library
          path: ./libstrmem.a
          restore-keys: |
            library-

      - name: gcc
        run: |
          gcc \
            -fPIE -std=c99 -Wall -Werror -Wextra -Wpedantic \
            tests/${{ matrix.test-name }}.c \
            -o ./${{ matrix.test-name }} \
            -L. -lstrmem

      - name: valgrind
        run: |
          valgrind \
            --error-exitcode=42 \
            --leak-check=full \
            --redzone-size=512 \
            --show-leak-kinds=all \
            ./${{ matrix.test-name }}
    strategy:
      matrix:
        test-name:
          - identity
          - similarity
          - valgrind

################################################################################
